### ISSUE TITLE
Support for fastify version 4

### ISSUE THREAD

**Issue by fmenis** [mcollina/fastify-massive#4]
Hi,
It would be great if this package will support the latest major of fastify (v4).
Is this change planned?
Greetings

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by fmenis** [comment]
Sure!
However, I can't imagine which kind of test should be written for testing a package's dependency upgrade.
There's no such test in the related `test.js` file.

**Comment by mcollina** [comment]
Shipped as v1.0.0! thanks!
